

#  Properties file for all files in this folder and below
#
#  The [database] section is required.
#
#  Ps, anything after the equals sign is added to the key
#  value.
#


[database]
DATABASE_HOST=D1-Yuga-C8N1
DATABASE_PORT=5433

DATABASE_NAME=my_db41

DATABASE_USER=yugabyte
DATABASE_PASSWORD=


APPLICATION_PORT=5041






