#  Properties file for all files in this folder and below
#
#  The [database] section is required.
#
#  PS: anything after the equals sign is added to the key value.
#

[database]
DATABASE_HOST=D1-ORA-C8N1
DATABASE_PORT=1521

DATABASE_NAME=my_db41

DATABASE_USER=oracle
DATABASE_PASSWORD=

APPLICATION_PORT=5041
